"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
import sharppy

sys.setrecursionlimit(2000)

APP = ['full_gui.py']
OPTIONS = {'argv_emulation': True,
	   'includes': ["PySide", "PySide.QtCore", "PySide.QtGui", "numpy", "sharppy"],
	   'excludes': ["scipy", "PyQt4", "basemap", "matplotlib"]} 
DATA_FILES = [('', ['datasources', 'shapefiles'])]
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
