# For this to be triggered, need to run the following:
# git tag -a v*.*.* -m 'Description of release.'
# git push origin v*.*.*

name: build
on:
  push:
    # branches:
    #   - main
    #   - master
    tags:
      - v*.*.*
  # schedule:
  #   - cron: '0 0 * * *'


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        python-version: [3.9]
        include:
          - os: [macos-latest, windows-latest]
          # - os: [windows-latest]

    # Control the os/python builds
    name: ${{ matrix.os }} Build and Release
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    # Installs environment
    - name: Install Conda and Environment
      uses: ./.github/actions/install-conda
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build binaries
      uses: ./.github/actions/run-build

    - name: Create Release
      # if: successful()
      uses: ./.github/actions/run-release
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
